name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build releases
        run: |
          mkdir build
          GOOS=windows GOARCH=amd64 go build -v -o build/yt-dlp-web-windows-amd64.exe ./...
          GOOS=windows GOARCH=arm64 go build -v -o build/yt-dlp-web-windows-arm64.exe ./...
          GOOS=linux GOARCH=amd64 go build -v -o build/yt-dlp-web-linux-amd64 ./...
          GOOS=linux GOARCH=arm64 go build -v -o build/yt-dlp-web-linux-arm64 ./...
          GOOS=darwin GOARCH=amd64 go build -v -o build/yt-dlp-web-darwin-amd64 ./...
          GOOS=darwin GOARCH=arm64 go build -v -o build/yt-dlp-web-darwin-arm64 ./...

      - name: Package releases
        run: |
          zip -j yt-dlp-web-windows-amd64.zip build/yt-dlp-web-windows-amd64.exe
          zip -j yt-dlp-web-windows-arm64.zip build/yt-dlp-web-windows-arm64.exe
          tar czvf yt-dlp-web-linux-amd64.tar.gz -C build yt-dlp-web-linux-amd64
          tar czvf yt-dlp-web-linux-arm64.tar.gz -C build yt-dlp-web-linux-arm64
          tar czvf yt-dlp-web-darwin-amd64.tar.gz -C build yt-dlp-web-darwin-amd64
          tar czvf yt-dlp-web-darwin-arm64.tar.gz -C build yt-dlp-web-darwin-arm64

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          prerelease: false
          body: |
            Changes for this release:
            - Add a list of changes here.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            yt-dlp-web-linux-amd64.tar.gz
            yt-dlp-web-linux-arm64.tar.gz
            yt-dlp-web-windows-amd64.zip
            yt-dlp-web-windows-arm64.zip
            yt-dlp-web-darwin-amd64.tar.gz
            yt-dlp-web-darwin-arm64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
